# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Или любая другая ветка, которую вы хотите использовать для деплоя

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Или другая версия Node.js 

      - name: Install Dependencies
        run: npm install # Или yarn install

      - name: Build Next.js
        run: npm run build # Или yarn build

      - name: Export Next.js
        run: npm run build && npm run export # Или yarn export (если используете next export)
                             # Замените на `npm run build && npm run export` если нужно и билдить и экспортировать

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Или ./dist, в зависимости от конфигурации next.config.js